# Generated by Django 4.2.25 on 2025-10-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdrecipe',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createdrecipe',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='createdrecipe',
            name='shared_message',
            field=models.TextField(blank=True, help_text='Optional message when sharing', null=True),
        ),
    ]
